import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { MiniApp } from '../miniapps/entities/miniapp.entity';

export interface OpenPrResult {
  status: 'no_changes' | 'skipped' | 'opened';
  prUrl?: string;
  prNumber?: number;
  supersededPrNumbers?: number[];
}

const CODEGEN_BRANCH_PREFIX = 'codegen/native-sdk-';

@Injectable()
export class GithubPrService {
  private readonly logger = new Logger(GithubPrService.name);

  constructor(
    private readonly configService: ConfigService,
    @InjectRepository(MiniApp)
    private readonly miniappRepository: Repository<MiniApp>,
  ) {}

  private enabled(): boolean {
    return this.configService.get<string>('CODEGEN_AUTO_PR') === 'true';
  }

  isEnabled(): boolean {
    return this.enabled();
  }

  private repoSlug(): string {
    const slug = this.configService.get<string>('CODEGEN_REPO_SLUG');
    if (!slug) {
      throw new Error('CODEGEN_REPO_SLUG must be set to open a PR (owner/repo)');
    }
    return slug;
  }

  private baseBranch(): string {
    return this.configService.get<string>('CODEGEN_BASE_BRANCH') || 'main';
  }

  private baseApiUrl(): string {
    return this.configService.get<string>('GITHUB_BASE_URL') || 'https://api.github.com';
  }

  private headers(): Record<string, string> {
    const token = this.configService.get<string>('GITHUB_TOKEN');
    return {
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'User-Agent': 'DPS-SuperApp-Integration',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };
  }

  private async githubFetch<T>(path: string, init?: RequestInit): Promise<T> {
    const res = await fetch(`${this.baseApiUrl()}${path}`, {
      ...init,
      headers: { ...this.headers(), ...((init?.headers as Record<string, string>) || {}) },
    });
    if (!res.ok) {
      const body = await res.text();
      this.logger.error(`GitHub API error on ${path} (${res.status}): ${body}`);
      throw new Error(`GitHub API error on ${path} (${res.status})`);
    }
    return res.json() as Promise<T>;
  }

  /**
   * Creates a branch, commit, and PR for the given changed files entirely
   * through the GitHub API, then closes any other open codegen PR against
   * the same base branch (superseded by this one, since regeneration always
   * covers every currently-approved vendor).
   */
  async openPrForChanges(changedFiles: Map<string, string>): Promise<OpenPrResult> {
    if (changedFiles.size === 0) {
      return { status: 'no_changes' };
    }
    if (!this.enabled()) {
      this.logger.log(
        `CODEGEN_AUTO_PR is not "true" — leaving ${changedFiles.size} regenerated file(s) unopened`,
      );
      return { status: 'skipped' };
    }

    const slug = this.repoSlug();
    const base = this.baseBranch();

    const baseRef = await this.githubFetch<{ object: { sha: string } }>(
      `/repos/${slug}/git/ref/heads/${base}`,
    );
    const baseSha = baseRef.object.sha;

    const baseCommit = await this.githubFetch<{ tree: { sha: string } }>(
      `/repos/${slug}/git/commits/${baseSha}`,
    );
    const baseTreeSha = baseCommit.tree.sha;

    const treeEntries: { path: string; mode: string; type: string; sha: string }[] = [];
    for (const [path, content] of changedFiles) {
      const blob = await this.githubFetch<{ sha: string }>(`/repos/${slug}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content, encoding: 'utf-8' }),
      });
      treeEntries.push({ path, mode: '100644', type: 'blob', sha: blob.sha });
    }

    const newTree = await this.githubFetch<{ sha: string }>(`/repos/${slug}/git/trees`, {
      method: 'POST',
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeEntries }),
    });

    const newCommit = await this.githubFetch<{ sha: string }>(`/repos/${slug}/git/commits`, {
      method: 'POST',
      body: JSON.stringify({
        message: 'chore(codegen): regenerate native SDK glue',
        tree: newTree.sha,
        parents: [baseSha],
      }),
    });

    const branch = `${CODEGEN_BRANCH_PREFIX}${Date.now()}`;
    await this.githubFetch(`/repos/${slug}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: newCommit.sha }),
    });

    const pr = await this.githubFetch<{ html_url: string; number: number }>(
      `/repos/${slug}/pulls`,
      {
        method: 'POST',
        body: JSON.stringify({
          title: 'Regenerate native SDK glue',
          head: branch,
          base,
          body: [
            'Generated by the Native SDK codegen script.',
            '',
            'Review before merging:',
            '- vendor deployment target / minSdk compatibility',
            '- declared permissions (iOS Info.plist strings do not auto-merge)',
            '',
            'Files changed:',
            ...Array.from(changedFiles.keys()).map(f => `- \`${f}\``),
          ].join('\n'),
        }),
      },
    );

    const supersededPrNumbers = await this.closeSupersededPrs(slug, base, pr.html_url, pr.number);

    this.logger.log(`Opened PR ${pr.html_url}`);
    return { status: 'opened', prUrl: pr.html_url, prNumber: pr.number, supersededPrNumbers };
  }

  private async closeSupersededPrs(
    slug: string,
    base: string,
    newPrUrl: string,
    newPrNumber: number,
  ): Promise<number[]> {
    const closed: number[] = [];
    let openPrs: { number: number; head: { ref: string } }[];
    try {
      openPrs = await this.githubFetch<{ number: number; head: { ref: string } }[]>(
        `/repos/${slug}/pulls?state=open&base=${encodeURIComponent(base)}`,
      );
    } catch (err) {
      this.logger.error(
        `Failed to list open PRs while checking for superseded codegen PRs: ${err}`,
      );
      return closed;
    }

    const superseded = openPrs.filter(
      p => p.number !== newPrNumber && p.head.ref.startsWith(CODEGEN_BRANCH_PREFIX),
    );

    for (const old of superseded) {
      try {
        await this.githubFetch(`/repos/${slug}/issues/${old.number}/comments`, {
          method: 'POST',
          body: JSON.stringify({
            body: `Superseded by a newer native SDK codegen run: ${newPrUrl}`,
          }),
        });
        await this.githubFetch(`/repos/${slug}/pulls/${old.number}`, {
          method: 'PATCH',
          body: JSON.stringify({ state: 'closed' }),
        });
        closed.push(old.number);
        await this.repointSupersededApps(old.number, newPrNumber, newPrUrl);
      } catch (err) {
        this.logger.error(`Failed to close superseded codegen PR #${old.number}: ${err}`);
      }
    }

    return closed;
  }

  /**
   * A mini app's lastCodegenRun.prNumber can point at a PR that has since been
   * closed as superseded (regeneration always covers every currently-approved
   * vendor, so a later approval's PR already contains everything an earlier
   * one had). Repoint every app tracking the just-closed PR at the new one, so
   * later correlation (e.g. "has this mini app's PR merged yet?") looks at the
   * PR that will actually ship its code, not a dead end.
   */
  private async repointSupersededApps(
    oldPrNumber: number,
    newPrNumber: number,
    newPrUrl: string,
  ): Promise<void> {
    try {
      const apps = await this.miniappRepository.find({
        where: { integrationMethod: 'NATIVE_SDK' } as any,
      });
      const affected = apps.filter(app => app.lastCodegenRun?.prNumber === oldPrNumber);
      for (const app of affected) {
        app.lastCodegenRun = {
          ...app.lastCodegenRun!,
          prNumber: newPrNumber,
          prUrl: newPrUrl,
        };
        await this.miniappRepository.save(app);
      }
      if (affected.length > 0) {
        this.logger.log(
          `Repointed ${affected.length} mini app(s) from superseded PR #${oldPrNumber} to #${newPrNumber}`,
        );
      }
    } catch (err) {
      this.logger.error(
        `Failed to repoint mini apps from superseded PR #${oldPrNumber} to #${newPrNumber}: ${err}`,
      );
    }
  }
}
