name: dps_miniapp_mobile_trust_regulator
description: "Trust Regulator Mini App with Restricted Hardware Permissions for Security Testing."
version: 1.2.0
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dps_core_package:
    path: ../dps_core_package
  nfc_manager: ^3.3.0
  flutter_blue_plus: ^1.35.4
  flutter_contacts: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
