name: dps_core_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://nd40vsdk-8081.asse.devtunnels.ms/repository/pub-group
publish_to: "https://nd40vsdk-8081.asse.devtunnels.ms/repository/pub-hosted"

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies: {}
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
