import 'package:flutter/material.dart';
import 'package:dsp_core/dsp_core.dart';
import 'package:dsp_miniapp_trust_regulator/dsp_miniapp_trust_regulator.dart';

void main() {
  runApp(const StandaloneExampleApp());
}

class StandaloneExampleApp extends StatelessWidget {
  const StandaloneExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    // This is the fake context generated by the standalone environment
    // In production, this context comes from the Super App via DI.
    final mockAuthContext = AuthContext(
      jwtToken: 'mock_jwt_token_for_standalone_testing',
      userId: 'test_user_123',
    );

    return MaterialApp(
      title: 'Trust Regulator Standalone Test',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blueGrey),
        useMaterial3: true,
      ),
      home: TrustRegulatorAppEntry(
        authContext: mockAuthContext,
        onExit: () {
          debugPrint('User requested to exit the mini app.');
        },
      ),
    );
  }
}
