name: superapp_mobile
description: "Super App Mobile Sandbox Simulator"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  webview_flutter: ^4.14.1
  http: ^1.6.0
  geolocator: ^14.0.3
  image_picker: ^1.2.3
  local_auth: ^3.0.2
  url_launcher: ^6.3.2

  sc_private_miniapp:
    git:
      url: https://github.com/KhornMolika/sc-private-miniapp.git
      ref: main
  dps_miniapp_mobile_trust_regulator:
    hosted:
      name: dps_miniapp_mobile_trust_regulator
      url: http://localhost:8081/repository/pub-group
    version: ^1.0.0
  sc_public_miniapp:
    git:
      url: https://github.com/KhornMolika/sc-public-miniapp.git
      ref: v1.0.0
  dps_miniapp_mobile_kyc_verifier:
    hosted:
      name: dps_miniapp_mobile_kyc_verifier
      url: http://localhost:8081/repository/pub-group
    version: ^1.0.0
  ma_flutter_kyc:
    hosted:
      name: ma_flutter_kyc
      url: http://localhost:8081/repository/pub-group
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
